Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmpv2kcy1zf/noarch/boltons-21.0.0-pyhd8ed1ab_0.tar.bz2
Reloading output folder: /home/vsts/conda/conda-bld

## Package Plan ##

  environment location: /home/vsts/conda/conda-bld/boltons_1636378913518/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge           conda-forge            
    _openmp_mutex:    4.5-1_gnu                 conda-forge            
    attrs:            21.2.0-pyhd8ed1ab_0       conda-forge            
    boltons:          21.0.0-pyhd8ed1ab_0       file:///tmp/tmpv2kcy1zf
    bzip2:            1.0.8-h7f98852_4          conda-forge            
    ca-certificates:  2021.10.8-ha878542_0      conda-forge            
    iniconfig:        1.1.1-pyh9f0ad1d_0        conda-forge            
    ld_impl_linux-64: 2.36.1-hea4e1c9_2         conda-forge            
    libffi:           3.4.2-h9c3ff4c_4          conda-forge            
    libgcc-ng:        11.2.0-h1d223b6_11        conda-forge            
    libgomp:          11.2.0-h1d223b6_11        conda-forge            
    libnsl:           2.0.0-h7f98852_0          conda-forge            
    libstdcxx-ng:     11.2.0-he4da1e4_11        conda-forge            
    libuuid:          2.32.1-h7f98852_1000      conda-forge            
    libzlib:          1.2.11-h36c2ea0_1013      conda-forge            
    more-itertools:   8.10.0-pyhd8ed1ab_0       conda-forge            
    ncurses:          6.2-h58526e2_4            conda-forge            
    openssl:          3.0.0-h7f98852_2          conda-forge            
    packaging:        21.2-pyhd8ed1ab_1         conda-forge            
    pip:              21.3.1-pyhd8ed1ab_0       conda-forge            
    pluggy:           1.0.0-py310hff52083_2     conda-forge            
    py:               1.11.0-pyh6c4a22f_0       conda-forge            
    pyparsing:        2.4.7-pyhd8ed1ab_1        conda-forge            
    pytest:           6.2.5-py310hff52083_1     conda-forge            
    python:           3.10.0-h543edf9_2_cpython conda-forge            
    python_abi:       3.10-2_cp310              conda-forge            
    readline:         8.1-h46c0cb4_0            conda-forge            
    setuptools:       58.5.3-py310hff52083_0    conda-forge            
    sqlite:           3.36.0-h9cd32fc_2         conda-forge            
    tk:               8.6.11-h27826a3_1         conda-forge            
    toml:             0.10.2-pyhd8ed1ab_0       conda-forge            
    tzdata:           2021e-he74cb21_0          conda-forge            
    wheel:            0.37.0-pyhd8ed1ab_1       conda-forge            
    xz:               5.2.5-h516909a_1          conda-forge            
    zlib:             1.2.11-h36c2ea0_1013      conda-forge            

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/vsts/conda/conda-bld/boltons_1636378913518/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export SRC_DIR=/home/vsts/conda/conda-bld/boltons_1636378913518/test_tmp
============================= test session starts ==============================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: $SRC_DIR, configfile: pytest.ini
collected 538 items / 3 errors / 535 selected

==================================== ERRORS ====================================
_____________________ ERROR collecting boltons/ecoutils.py _____________________
boltons/ecoutils.py:357: in <module>
    _real_safe_repr = pprint._safe_repr
E   AttributeError: module 'pprint' has no attribute '_safe_repr'
___________________ ERROR collecting tests/test_ecoutils.py ____________________
tests/test_ecoutils.py:3: in <module>
    from boltons import ecoutils
boltons/ecoutils.py:357: in <module>
    _real_safe_repr = pprint._safe_repr
E   AttributeError: module 'pprint' has no attribute '_safe_repr'
___________________ ERROR collecting tests/test_ecoutils.py ____________________
tests/test_ecoutils.py:3: in <module>
    from boltons import ecoutils
boltons/ecoutils.py:357: in <module>
    _real_safe_repr = pprint._safe_repr
E   AttributeError: module 'pprint' has no attribute '_safe_repr'
=========================== short test summary info ============================
ERROR boltons/ecoutils.py - AttributeError: module 'pprint' has no attribute ...
ERROR tests/test_ecoutils.py - AttributeError: module 'pprint' has no attribu...
ERROR tests/test_ecoutils.py - AttributeError: module 'pprint' has no attribu...
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 1.13s ===============================

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


