Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmpno3m996h/linux-64/zifa-0.1.0-py36_0.tar.bz2
Adding in variants from internal_defaults
Reloading output folder: /home/vsts/conda/conda-bld
Mamba failed to solve:
 - zifa 0.1.0.* py39_0
 - python
 - python

with channels:
 - file:///tmp/tmpno3m996h

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested zifa 0.1.0.* py39_0
- 

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


