Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmp4dp7hf04/linux-64/manormfast-0.1.2-py36_1.tar.bz2
Adding in variants from internal_defaults
Reloading output folder: /home/vsts/conda/conda-bld
Mamba failed to solve:
 - manormfast 0.1.2.* py39_1
 - python
 - numpy
 - scipy
 - statsmodels
 - matplotlib
 - python

with channels:
 - file:///tmp/tmp4dp7hf04

The reported errors are:
   Encountered problems while solving:
     - nothing provides requested manormfast 0.1.2.* py39_1
   

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


