Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmpox09hten/noarch/nanoplot-1.38.1-pyhdfd78af_0.tar.bz2
Mamba failed to solve:
 - nanoplot 1.38.1 pyhdfd78af_0
 - biopython
 - libpng
 - nanoget >=1.14.0
 - nanomath >=1.2.1
 - numpy
 - pandas >=1.1.0
 - plotly >=4.9.0
 - pyarrow
 - pysam >0.10.0.0
 - python >=3
 - python-dateutil
 - python-kaleido
 - scipy
 - python

with channels:
 - file:///tmp/tmpox09hten

The reported errors are:
   Encountered problems while solving:
     - nothing provides __glibc >=2.17,<3.0.a0 needed by kaleido-core-0.1.0-h3644ca4_0
     - nothing provides __glibc >=2.17,<3.0.a0 needed by kaleido-core-0.1.0-h3644ca4_0
   

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


