Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmp22ged_ey/noarch/dropbox-11.20.0-pyhd8ed1ab_0.tar.bz2
Mamba failed to solve:
 - dropbox 11.20.0 pyhd8ed1ab_0
 - python =2.7|>=3.4
 - requests >=2.16.2
 - six >=1.12.0
 - stone >=2
 - pytest-mock
 - coverage
 - mock
 - pip
 - python

with channels:
 - file:///tmp/tmp22ged_ey

The reported errors are:
   Encountered problems while solving:
     - nothing provides __unix needed by stone-3.2.1-pyhd8ed1ab_0
     - nothing provides __unix needed by stone-3.2.1-pyhd8ed1ab_0
   

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


