Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmpx8y3qk1a/linux-64/py-graphviz-0.4.10-py36_0.tar.bz2
Adding in variants from internal_defaults
Reloading output folder: /home/vsts/conda/conda-bld
Mamba failed to solve:
 - py-graphviz 0.4.10.* py39_0
 - python
 - python

with channels:
 - file:///tmp/tmpx8y3qk1a

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested py-graphviz 0.4.10.* py39_0
- 

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


